apiVersion: v1
kind: PersistentVolumeClaim
namespace: lab3
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 4Gi
