apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-manual
spec:
  capacity: 
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: localstorage
  hostPath:
    path: /tmp/mysql 
