apiVersion: v1
kind: Service
metadata: 
  name: lbservice-app
  namespace: lab3
  labels:
    name: loadbalancer-app
    app: employees
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: employees
  type: LoadBalancer
