apiVersion: v1
kind: Service
metadata: 
  name: lbservice-app
  labels:
    name: loadbalancer-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: employees
  type: LoadBalancer
